Remove Principal Check
RedHatInsights/insights-rbac pull request #1137
Opened 2024-07-03 18:45 UTC by Ellen-Yi-Dong

## Link(s) to Jira
-https://issues.redhat.com/browse/RHCLOUD-33727

## Description of Intent of Change(s)
The what, why and how.
Need to remove principal check in order to make sure that the PR checks work and is in relation to the updates that were made by performance team 

"We need to determine if the principal check in the audit log model at [this location](https://github.com/RedHatInsights/insights-rbac/blob/master/rbac/management/audit_log/model.py#L104) is necessary.

This check causes issues in the development environment or when custom data is populated, particularly when the user is not yet created in the database.

 

Current Problem:

    The principal check leads to issues when the performance team runs their script, which first creates roles and then principals. This sequence causes errors as the principal is not found.
        Alternative is to discuss with the performance team to understand the sequence of their script and explore the possibility of changing the order to create principals before roles.
    There is a possibility that the principal existence check is already being handled elsewhere in the codebase.

 

Proposed Solution:

Consider bypassing the principal check by directly using the username and ID from the request." 
## Local Testing
How can the feature be exercised?
How can the bug be exploited and fix confirmed?
Is any special local setup required?

## Checklist
- [ ] if API spec changes are required, is the spec updated?
- [ ] are there any pre/post merge actions required? if so, document here.
- [ ] are theses changes covered by unit tests?
- [ ] if warranted, are documentation changes accounted for?
- [ ] does this require migration changes?
  - [ ] if yes, are they backwards compatible?
- [ ] is there known, direct impact to dependent teams/components?
  - [ ] if yes, how will this be handled?

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Practices Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-07-03 19:14 UTC, Ellen-Yi-Dong commented
/retest

2024-07-04 10:00 UTC, petracihalova commented on rbac/management/audit_log/model.py
> +        self.principal_id = request.user.user_id
curious question, here the `get_resource_time` method is not called anymore ... do we still need then this part? but I dont have strong preferences ❤️ https://github.com/RedHatInsights/insights-rbac/blob/34cb1b4d3398d254a599675eb83f84cf40d36a79/rbac/management/audit_log/model.py#L98-L100

2024-07-04 16:18 UTC, vbelchio requested changes

2024-07-04 16:18 UTC, vbelchio commented on rbac/management/audit_log/model.py
>      def log_create(self, request, resource):
@Ellen-Yi-Dong Checking the PR_check failure we have a constraint violation in the `management_auditlog`.
Using a fresh database, I tried to create a new role and got this error due to not have the user requester as a principal yet:
```
{
  "errors": [
    {
      "detail": "insert or update on table \"management_auditlog\" violates foreign key constraint \"management_auditlog_principal_id_512ce4d0_fk_managemen\"\nDETAIL:  Key (principal_id)=(51834776) is not present in table \"management_principal\".\n",
      "source": "role",
      "status": "400"
    }
  ]
}
```

Maybe we can check and add the user requester as a principal inside the `log_create` method.

2024-07-11 15:59 UTC, closed without merging