[RHCLOUD-33414] - restrict the Custom default access group renaming
RedHatInsights/insights-rbac pull request #1383
Opened 2024-12-11 10:50 UTC by EvanCasey13

## Link(s) to Jira
https://issues.redhat.com/browse/RHCLOUD-33414

## Description of Intent of Change(s)

## Local Testing
How can the feature be exercised?
How can the bug be exploited and fix confirmed?
Is any special local setup required?

## Checklist
- [ ] if API spec changes are required, is the spec updated?
- [ ] are there any pre/post merge actions required? if so, document here.
- [ ] are theses changes covered by unit tests?
- [ ] if warranted, are documentation changes accounted for?
- [ ] does this require migration changes?
  - [ ] if yes, are they backwards compatible?
- [ ] is there known, direct impact to dependent teams/components?
  - [ ] if yes, how will this be handled?

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Practices Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2024-12-11 11:13 UTC, EvanCasey13 commented
/retest

2024-12-11 16:09 UTC, astrozzc commented on rbac/management/group/view.py
> +        self.restrict_custom_default_group_renaming(request)
If you put this after the group = self.get_object(), you can check if the group is custom default group by group.platform_default. Which will simplify your method a lot

2024-12-11 17:33 UTC, astrozzc commented on rbac/management/group/view.py
> +            self.restrict_custom_default_group_renaming(request)
Since you get the group above, you can put it into the method. If the name/description different from group.name/description, raise validation error

2024-12-12 13:35 UTC, astrozzc commented on rbac/management/group/view.py
> +            is_custom_group = (
you can use `group.platform_default and not group.system` to determine it is custom default group. You can

2024-12-12 13:56 UTC, EvanCasey13 commented
/retest

2024-12-12 14:44 UTC, lpichler commented on rbac/management/group/view.py
> +    def restrict_custom_default_group_renaming(self, request, group):
This method does multiple  things:
- check HTTP method
- check custom group
- raise Validation error 

Is there a change to split it ? More details in comments

Can this logic be part only of update operation ? (So we don't need check on  HTTP method)

2024-12-12 14:48 UTC, lpichler commented on rbac/management/group/view.py
> +            key = "Custom default group"
is to possible to keep this consistent across app ? key is `detail` - it refers to this https://datatracker.ietf.org/doc/html/rfc7807#section-3.1

2024-12-12 14:49 UTC, lpichler commented on tests/management/group/test_view.py
> +        self.Custom_default_group = Group(
nit: I think preferred is lower case.

2024-12-12 17:04 UTC, astrozzc approved these changes
LGTM!

2024-12-12 17:04 UTC, astrozzc commented on rbac/management/group/serializer.py
> +        return False
You can do return group.platform_default and not group.system

2024-12-20 08:00 UTC, petracihalova commented on rbac/management/group/serializer.py
> +            message = "Updating the name or description of Custom default group is restricted"
nitpick: it would be nice to have the name of the group in single quotes to distinguish what is name group

2024-12-20 08:04 UTC, petracihalova commented on rbac/management/group/serializer.py
> +            error = {key: [(message)]}
I believe the parentheses here are not needed
`error = {key: [message]}`

2024-12-20 17:43 UTC, petracihalova requested changes
hi Evan, thank you for the change, but we need to review it a little bit, please after you try to change the `Custom default access` group and you get 400 (that is expected), check the data from database and you will see the record was changed, that is because `self.restrict_custom_default_group_renaming(group)` is called after `group = super().update(instance, validated_data)`. 

```
    def update(self, instance, validated_data):
        """Update the role object in the database."""
        group = super().update(instance, validated_data)
        self.restrict_custom_default_group_renaming(group)
        group_obj_change_notification_handler(self.context["request"].user, group, "updated")
        return group
```

I think we should use different direction here, I am open to discussion because I am not so experienced here and maybe we can use something similar as `protect_system_groups()` in the view ([here](https://github.com/RedHatInsights/insights-rbac/blob/878fbb81f0997274384e27c01d063952c64e71ba/rbac/management/group/view.py#L438)), and we should still keep in mind that it is possible to delete this group and add and remove roles from it

one option is to add new condition into `protect_system_groups()`, for example something like

```
    def protect_system_groups(self, action, group=None):
        """Deny modifications on system groups."""
        if group is None:
            group = self.get_object()
        if group.system:
            key = "group"
            message = "{} cannot be performed on system groups.".format(action.upper())
            error = {key: [_(message)]}
            raise serializers.ValidationError(error)
        if group.platform_default and action == "update":
            key = "group"
            message = "It is not allowed to change name or description of the 'Custom default access' group."
            error = {key: [_(message)]}
            raise serializers.ValidationError(error)
```
cc: @lpichler @astrozzc

2025-01-02 09:46 UTC, astrozzc commented
> hi Evan, thank you for the change, but we need to review it a little bit, please after you try to change the `Custom default access` group and you get 400 (that is expected), check the data from database and you will see the record was changed, that is because `self.restrict_custom_default_group_renaming(group)` is called after `group = super().update(instance, validated_data)`.
> 
> ```
>     def update(self, instance, validated_data):
>         """Update the role object in the database."""
>         group = super().update(instance, validated_data)
>         self.restrict_custom_default_group_renaming(group)
>         group_obj_change_notification_handler(self.context["request"].user, group, "updated")
>         return group
> ```
> 
> I think we should use different direction here, I am open to discussion because I am not so experienced here and maybe we can use something similar as `protect_system_groups()` in the view ([here](https://github.com/RedHatInsights/insights-rbac/blob/878fbb81f0997274384e27c01d063952c64e71ba/rbac/management/group/view.py#L438)), and we should still keep in mind that it is possible to delete this group and add and remove roles from it
> 
> one option is to add new condition into `protect_system_groups()`, for example something like
> 
> ```
>     def protect_system_groups(self, action, group=None):
>         """Deny modifications on system groups."""
>         if group is None:
>             group = self.get_object()
>         if group.system:
>             key = "group"
>             message = "{} cannot be performed on system groups.".format(action.upper())
>             error = {key: [_(message)]}
>             raise serializers.ValidationError(error)
>         if group.platform_default and action == "update":
>             key = "group"
>             message = "It is not allowed to change name or description of the 'Custom default access' group."
>             error = {key: [_(message)]}
>             raise serializers.ValidationError(error)
> ```
> 
> cc: @lpichler @astrozzc

2025-01-02 10:01 UTC, astrozzc commented
Yea, thanks Petra, good catch!!! And I agree putting the function inside the view seems to be appropriate.

The `protect_system_groups` has been used in several places, it is better have a separate function `restrict_custom_default_group_renaming` next to `protect_system_groups`, so that we don't run this checking of renaming logic only when necessary.

2025-01-02 10:07 UTC, astrozzc commented
Yea, thanks Petra, good catch!!! And I agree putting the function inside the view seems to be appropriate.

The `protect_system_groups` has been used in several places, it is better have a separate function `restrict_custom_default_group_renaming` next to `protect_system_groups`, so that we don't run this checking of renaming logic only when necessary.

2025-01-21 19:51 UTC, vbelchio commented
QE: Passed

2025-01-29 21:14 UTC, petracihalova approved these changes

2025-01-29 21:14 UTC, petracihalova commented on tests/management/group/test_view.py
> +
nice job 👍 I have small nitpick ... I would like to check not only status code but the text of the err message to be 100% sure that rbac returns 400 from correct condition, for example something like this
```
 expected_err_message = "Updating the name or description of 'Custom default group' is restricted"
 self.assertEqual(response.data.get("errors")[0].get("detail"), expected_err_message)
```
you can add it if you want but for now we can merge this PR

2025-01-29 21:34 UTC, merged